/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webgpucontext_free: (a: number, b: number) => void;
export const __wbg_yapoengine_free: (a: number, b: number) => void;
export const webgpucontext_new_js: () => any;
export const yapoengine_clear_gpu_context: (a: number) => void;
export const yapoengine_get_epoch: (a: number) => number;
export const yapoengine_get_vocab_size: (a: number) => number;
export const yapoengine_get_vocab_snapshot_json: (a: number) => [number, number];
export const yapoengine_load_model_bytes: (a: number, b: number, c: number) => number;
export const yapoengine_load_text: (a: number, b: number, c: number, d: number) => void;
export const yapoengine_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => number;
export const yapoengine_predict: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const yapoengine_save_model_bytes: (a: number, b: number) => [number, number];
export const yapoengine_set_batch_size: (a: number, b: number) => void;
export const yapoengine_set_gpu_context: (a: number, b: number) => void;
export const yapoengine_set_layer_filter: (a: number, b: number) => void;
export const yapoengine_set_lr_model: (a: number, b: number) => void;
export const yapoengine_set_lr_vocab: (a: number, b: number) => void;
export const yapoengine_set_opt_type: (a: number, b: number) => void;
export const yapoengine_set_stochastic_freq: (a: number, b: number) => void;
export const yapoengine_set_stochastic_pct: (a: number, b: number) => void;
export const yapoengine_set_train_vocab: (a: number, b: number) => void;
export const yapoengine_set_weight_strategy: (a: number, b: number) => void;
export const yapoengine_step_training: (a: number, b: number) => any;
export const yapoengine_stream_start: (a: number, b: number, c: number) => void;
export const yapoengine_stream_step: (a: number, b: number) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__ha3fc3a660cd53d94: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5d2b72d30e2f7453: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a93edd5bf26d7ea: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0a93edd5bf26d7ea_2: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
